# api_agent.py

import asyncio
import gc
from abc import ABC, abstractmethod

from api_llm_handling import AgentCall
from api_agent_classes import APIType

class APIAgent(ABC):
    def __init__(self, fast_mode=False, api="generic", retry_cap=10, from_user=True, credentials = None):
        """Initialize a generic API-based LLM agent."""
        self.api = APIType.from_string(api)

        self.from_user = from_user

        # Control events
        self.stop_event = asyncio.Event()
        self.cleaned_up = asyncio.Event()

        self.fast_mode = fast_mode
        self.retry_cap = retry_cap

        # Inputs or prompts
        self.task = None  # The main user request
        self.task_notes = ''  # Additional context

        # For LLM question/answer flows
        self.question_answers = []  # To track what the child class asks the user

        # For memory, record all actions
        self.action_mem = []

        # Hidden or default fields for user
        self.hidden_inputs = []

        # Queues for user I/O
        self.input_queue = asyncio.Queue()
        self.output_queue = asyncio.Queue()

        # Track attempts
        self.failed_count = 0
        self.reload_count = 0

        # Additional context from knowledge base
        self.context_info = ""  # May be needed by the child class
        self.item_context_pairs = ""  # May be needed by the child class

        #store credentials in user object
        self.credentials = credentials
        
        self.initialize_api_handler()

    @abstractmethod
    def initialize_api_handler(self):
        """Initialize the appropriate API handler based on self.api."""
        pass

    @abstractmethod
    def setup(self):
        """Setup tasks specific to the child agent before running."""
        pass

    async def ask_user(self, question):
        """Ask the user a question asynchronously; wait for a response."""
        await self.output_queue.put(('question', question))
        while not self.stop_event.is_set():
            try:
                response = await asyncio.wait_for(self.input_queue.get(), timeout=0.1)
                return response
            except asyncio.TimeoutError:
                continue
        raise InterruptedError("Agent stopped")

    @abstractmethod
    async def handle_actions(self, action):
        """Handle actions generated by the LLM. To be implemented by child classes."""
        pass

    async def run(self):
        """Main execution loop for the agent."""
        # Perform setup tasks specific to the child agent
        await self.setup()

        # Main loop to process actions
        while not self.stop_event.is_set():
            try:
                # a) LLM decides on next action => we get an `AgentCall`
                action_out_call = await self.call_action()
                chosen_action = action_out_call.parsed_output

                if not chosen_action:
                    # If it's None or empty, treat as failure
                    self.failed_count += 1
                    if self.failed_count > self.retry_cap:
                        self.stop()
                    continue

                # Delegate action handling to the child class
                await self.handle_actions(chosen_action)

                gc.collect()

            except Exception as e:
                print(f"Agent encountered exception: {e}")
                if self.stop_event.is_set():
                    await self.cleanup()
                else:
                    self.failed_count += 1
                    if self.failed_count > self.retry_cap:
                        self.stop()
            finally:
                if self.stop_event.is_set():
                    await self.cleanup()

    @abstractmethod
    async def call_action(self) -> AgentCall:
        """Call the LLM to decide the next action. To be implemented by child classes."""
        pass

    async def cleanup(self):
        """Cleanup any resources if needed."""
        gc.collect()
        self.cleaned_up.set()

    def stop(self):
        """Stop execution."""
        self.stop_event.set()
